haiku/haikuwebkit

Source/WebCore/platform/graphics/haiku/FontHaiku.cpp
Source/WebCore/platform/graphics/haiku/SimpleFontDataHaiku.cpp

After f1c80ff75 the .notdef glyph may be requested on purpose. That's
unfortunate for us because we map glyphs to Unicode characters, there's
no character for that, its code is 0 and it becomes a NULL character
that is not added to the string, making advances out of sync.
The purpose of the change was to force some control characters to be
visible, so instead of removing it and align advances, we replace it
with U+FFD1, which is defined as a noncharacter available to programmers
for internal processing purposes. Except for special purpose fonts, it
shouldn't have a glyph to draw, so the font backend will use .notdef in
the end.
Fixes https://dev.haiku-os.org/ticket/17258

Fix text garbling when the .notdef glyph is used

---

Source/WebCore/platform/graphics/haiku/GraphicsContextHaiku.cpp

`drawLine` arguments are the corners of the rectangle containing the border piece.
`drawLinesForText` was not setting the pen width.
Feel free to squash after review.

Fix skewed borders and text-decoration thickness

---

Source/WebCore/platform/graphics/haiku/GraphicsContextHaiku.cpp

The GraphicsContextState does not have the same default values as our view, so we may use the wrong ones. For an example, notice the lack of black areas when opening Haiku's [lion.svg test](https://github.com/haiku/haiku/blob/master/src/tests/kits/interface/picture/lion.svg).
The call to `didUpdateState` does not seem to be strictly necessary, as webkit is quite spammy calling that by itself even with no changes, but that may change in the future.
Another thing that seems to work is setting the change flags unconditionally as is done for Cairo ([here](https://github.com/haiku/haikuwebkit/blob/c7f2d7a6f4cd17d7b453523302e45e3d48bc93a5/Source/WebCore/platform/graphics/GraphicsContextState.h#L144) nad  [here](https://github.com/haiku/haikuwebkit/blob/c7f2d7a6f4cd17d7b453523302e45e3d48bc93a5/So …

Sync view and graphics context state on creation

---

Source/WebKitLegacy/haiku/API/WebPage.cpp
Source/WebKitLegacy/haiku/API/WebPage.h
Source/WebKitLegacy/haiku/WebCoreSupport/ChromeClientHaiku.cpp

Should fix https://dev.haiku-os.org/ticket/15625

BWebPage's createNewPage method now requires a BUrlContext

---

Source/WebKitLegacy/haiku/API/WebFrame.cpp
Source/WebKitLegacy/haiku/API/WebFramePrivate.h

Remove code that isn't in the windows version of WebKitLegacy. However this is not sufficient, the infinite loop is gone but now we get a crash in BReferenceable at exit because some objects are still being referenced.

Fix infinite loop when loading pages

---

Source/WebCore/platform/graphics/haiku/GraphicsContextHaiku.cpp

Fixes the problems in [17305](https://dev.haiku-os.org/ticket/17305) for SVG. The ones with transparency layers have a different cause.

GraphicsContext: fix clipBounds

---

Source/WebCore/platform/graphics/haiku/ImageBufferHaiku.cpp

Brings back the gradient for not-hovered items in the menu bar in https://dev.haiku-os.org/.
Bisecting pointed to 5726cb78f5, where copyImage is devirtualized and calls copyNativeImage, so we lost our Sync. I don't know whether that is needed for both doCopy cases (putting it in the DontCopyBackingStore route seems to be enough) and why it wasn't needed before there.

ImageBuffer: sync view on image copy

---

Source/WebCore/platform/haiku/LoggingHaiku.cpp
Source/WebKitLegacy/haiku/API/WebPage.cpp
Source/WebKitLegacy/haiku/WebCoreSupport/FullscreenVideoController.cpp

Source/WebCore/platform/haiku/LoggingHaiku.cpp:
Source/WebKitLegacy/haiku/API/WebPage.cpp:
* There is no converting constructor in WTF::String for const char*, so use String::fromUTF8.
Source/WebKitLegacy/haiku/WebCoreSupport/FullscreenVideoController.cpp:
* FullscreenVideoController::exitFullscreen() had an assert for a member variable that no longer exists. Deleted this assertion.

Fix minor issues with debug build

---

Source/WebKitLegacy/haiku/API/WebDownloadPrivate.cpp

m_filename contains just the file name, not the full path, so the Node creation failed.
We should also set it even if we don't have a mime type.
Fixes https://dev.haiku-os.org/ticket/18227

Fix saving META:url attribute on downloads

---

Source/WebKitLegacy/haiku/WebCoreSupport/ChromeClientHaiku.cpp
Source/WebKitLegacy/haiku/WebCoreSupport/InspectorClientHaiku.cpp

These are handled by smart pointers since c4ee0780b3981bc7c1a6e4e0772a003e2e66bf61.

Fix double delete

---

Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml

Recover the value of ShrinksStandaloneImagesToFit that was lost when the WebPreferences files were unified.
Fixes https://dev.haiku-os.org/ticket/18360

Fit images to window size

---

Source/WebCore/platform/graphics/haiku/FontHaiku.cpp

WebKit adds a 0 glyph that shapers are supposed to remove and we were drawing as if it came from a real character.
Fix some warnings while we are at it.

Remove extra character after those out of the BMP

---

Source/WebKit/PlatformHaiku.cmake
Source/WebKit/UIProcess/Launcher/haiku/ProcessLauncherHaiku.cpp
Tools/MiniBrowser/haiku/CMakeLists.txt

Also make MiniBrowser crash earlier if one of these executables is missing.

Compile NetworkProcess and WebProcess along with MiniBrowser

---

Source/WebKit/UIProcess/API/haiku/PageClientImplHaiku.cpp
Source/WebKit/UIProcess/API/haiku/WebViewBase.cpp
Source/WebKit/UIProcess/API/haiku/WebViewBase.h

WebKit's UIProcess tends to want things to only be done from one thread. In our case, this is the BApplication thread. We were calling setSize from a BWindow thread. This lead to an assert testing whether we were on the right thread failing.
This change removes the call to setSize from WebViewBase::Draw. This fixes the crash, but also leaves the drawing area size at 0x0. The update to the definition of PageClientImpl::viewSize fixes this. It also seems like the correct definition of viewSize.

Do not set drawing area size outside of main thread

---

Source/WebCore/platform/graphics/FontCascade.cpp
Source/WebCore/platform/graphics/haiku/ComplexTextControllerHaiku.cpp
Source/WebCore/platform/graphics/haiku/FontCustomPlatformData.cpp
Source/WebCore/platform/graphics/haiku/FontHaiku.cpp

The hack in FontHaiku.cpp to set the code path to simple does not work for WebKit2 since WebKit2 sets the code path to CodePath::Auto later. Always returning CodePath::Simple from FontCascade::codePath works for WebKitLegacy and WebKit2.

Always use CodePath::Simple to render fonts

---

README.markdown
Source/WTF/Scripts/generate-unified-source-bundles.rb
Source/WebCore/Sources.txt

Its complexity is big enough on its own when compiled on x86.
The script is changed so that, as a derived source not existing when it is run, it takes it anyway, creating a "bundle" that includes just that file and removing it from the one it would have been in.

Mark JSDOMWindow.cpp to not be bundled

---

Source/WebCore/platform/graphics/ComplexTextController.cpp
Source/WebCore/platform/graphics/FontCascade.cpp
Source/WebCore/platform/graphics/FontCascade.h

Disable complex text path in more cases and an environment variable protected call to debugger to detect issues that might be related to it.

Reduce complex text

---

Source/WTF/wtf/posix/FileSystemPOSIX.cpp

After the first call it would fall down with no return instruction.

FileSystemPOSIX: return temp dir in subsequent calls

---

Source/WebCore/platform/network/curl/CurlDownload.cpp
Source/WebCore/platform/network/curl/CurlDownload.h

Fixes download of attachments in anubis protected trac.
This is NOT the result of any understanding of how it should work. I failed hard when I tried, lost in the forest of loaders, handlers, delegates, raw/sub/cached resources and whatnot the execution goes through after clicking a link. The only clear information I got is that when it gets here, the request doesn't have the cookies header. For the download link option from the context menu it's more straightforward: a request is made from the URL and gets here quite directly, just URL and Accept-Language, without even User-Agent, Accept or Referer.

[curl] Set cookies for download requests

---

Tools/DumpRenderTree/haiku/DumpRenderTree.cpp

So that they match the format expected by the automated tests.

DRT: remove line number from console messages
